FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ENV NODE_ENV=production
ARG NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
ARG DB_URL
ENV DB_URL=${DB_URL}
ARG JWT_SECRET
ENV JWT_SECRET=${JWT_SECRET}

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"] 