export const monthsMap: { [key: string]: number } = {
  styczeń: 0,
  stycznia: 0,
  luty: 1,
  lutego: 1,
  marzec: 2,
  marca: 2,
  kwiecień: 3,
  kwietnia: 3,
  maj: 4,
  maja: 4,
  czerwiec: 5,
  czerwca: 5,
  lipiec: 6,
  lipca: 6,
  sierpień: 7,
  sierpnia: 7,
  wrzesień: 8,
  września: 8,
  październik: 9,
  października: 9,
  listopad: 10,
  listopada: 10,
  grudzień: 11,
  grudnia: 11,
};
